### PR TITLE
Added support for PR templates

### LINKED ISSUE #12: Is there any way to bring in the template from the .github/PULL_REQUEST_TEMPLATE.md
As then this would automatically contain everything ready for filling out as part of the review.

### PR DESCRIPTION
**Pull request by ChristophShyper**
This is to resolved #12

It introduces `pr_template` input with a path to a file in repository as a value.

File is parsed and characters '`' and '$' are escaped in case they were used in the template.

### CODE REVIEW

**Comment by ChristophShyper** [comment]
@wei can you have a look?

**Comment by wei** [comment]
Thanks for the PR! I'll spend some time and merge after testing!

**Comment by wei** [comment]
@all-contributors add @ChristophShyper for code

**Comment by ChristophShyper** [comment]
Glad I could help :)

**Pull request merged**
